version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

executors:
  default:
    docker:
      - image: cimg/ruby:3.1.2-node
    environment:
      RAILS_ENV: test
      RACK_ENV: test

jobs:
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check

  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake db:test:prepare
      - ruby/rspec-test

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec
